'use client';
import type { Metadata } from "next";
import { Provider } from "react-redux";
import localFont from "next/font/local";
import Header from "@/components/Header";
import { store } from "../redux/store"; // Import the Redux store
import "./globals.css"; // Import global styles

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

<head>
  <title>Create Next App</title>
  <meta name="description" content="Generated by create next app" />
</head>

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider store={store}> 
          <main>
            <Header />
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
